'use strict';
const C=Core,E=C.escape,$=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let appliedHash='',route='',modalReturn=null,busy=false,searchTimer,toastTimer,editingDashboard=null,selectedClient='',lastSuggestion=null;
let selectedBills=new Set(),tourIndex=0,calendarMonth='',installPrompt=null;
const icon=(name)=>{const paths={grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z',users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8M17 4a4 4 0 0 1 0 7M22 21v-2a4 4 0 0 0-3-3.9',bill:'M5 3h14v18l-3-2-4 2-4-2-3 2zM8 7h8M8 11h8M8 15h5',clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',chat:'M21 11a8 8 0 0 1-8 8H7l-5 3 1-7a8 8 0 0 1 10-12 8 8 0 0 1 8 8',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 2v3M12 19v3M2 12h3M19 12h3M5 5l2 2M17 17l2 2M19 5l-2 2M7 17l-2 2',arrow:'M5 12h14M13 6l6 6-6 6',menu:'M3 6h18M3 12h18M3 18h18',sun:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8M12 1v3M12 20v3M1 12h3M20 12h3',plus:'M12 5v14M5 12h14',check:'M5 12l4 4L19 6',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',close:'M6 6l12 12M6 18L18 6'};return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${paths[name]||paths.grid}"/></svg>`;};
const btn=(label,act,id='',cls='')=>`<button type="button" class="btn ${cls}" data-action="${act}" data-id="${E(id)}">${label}</button>`;
const opt=(val,label,current)=>`<option value="${E(val)}" ${val===current?'selected':''}>${E(label)}</option>`;
const field=(name,label,value='',type='text',extra='')=>`<div class="field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${E(value)}" ${extra}></div>`;
const badge=b=>`<span class="badge ${C.status(b,Store.get().today)}">${{pago:'Pago',pendente:'Pendente',atrasado:'Atrasado'}[C.status(b,Store.get().today)]}</span>`;
const person=id=>Store.get().clients.find(c=>c.id===id);
const bill=id=>Store.get().bills.find(b=>b.id===id);
const short=(s,n=80)=>E(s.length>n?s.slice(0,n)+'…':s);
function toast(text,undo){clearTimeout(toastTimer);$('#toast').hidden=false;$('#toast').innerHTML=`<span>${E(text)}</span>${undo?btn('Desfazer','undo-suggestion'):''}${btn('Fechar','close-toast')}`;toastTimer=setTimeout(()=>$('#toast').hidden=true,7000);}
function openModal(title,content){modalReturn=document.activeElement;$('#modal-title').textContent=title;$('#modal-body').innerHTML=`<div class="dialog-error error" role="alert" tabindex="-1"></div>${content}`;$('#dialog').showModal();setTimeout(()=>$('#modal-body input:not([disabled]),#modal-body select,#modal-body button')?.focus(),0);}
function closeModal(){if(busy)return;$('#dialog').close();modalReturn?.focus();}
function error(message){const el=$('#dialog[open] .dialog-error')||$('#page-error');el.hidden=false;el.textContent=message;el.focus();}
async function commit(action,data,success,after){if(busy)return;busy=true;updateConnection(true);const d=$('#dialog');const forms=$$('button[type=submit],#dialog [data-action^="confirm-"],#dialog [data-action="save-dashboard"],#dialog [data-action="api-send"]');forms.forEach(b=>{b.disabled=true;b.dataset.label=b.textContent;b.textContent='Salvando…';});try{await Store.mutate(action,data);busy=false;if(d.open)d.close();render();$('h1')?.focus({preventScroll:true});if(data.id)document.querySelector('[data-bill-id="'+CSS.escape(data.id)+'"]')?.classList.add('flash');toast(success+(Store.real?'':' · salvo neste navegador'));after?.();}catch(e){error(e.message);}finally{busy=false;updateConnection();forms.forEach(b=>{b.disabled=false;b.textContent=b.dataset.label;});}}
function heading(title,sub,actions=''){return `<div class="page-heading"><div><p class="eyebrow">GESTOR DE CLIENTES E COBRANÇAS</p><h1 tabindex="-1">${E(title)}</h1><p class="muted">${E(sub)}</p></div><div class="actions">${actions}</div></div>`;}
function metadata(){return `<div class="widget-meta">Atualizado ${new Date(Store.get().updated).toLocaleTimeString('pt-BR',{hour:'2-digit',minute:'2-digit'})} · ${C.date(Store.get().today)}</div>`;}
function chartWidget(){const series=Advanced.monthly(Store.get()),max=Math.max(1,...series.flatMap(x=>[x.paid,x.pending]));return `<div class="panel-body"><div class="chart" role="img" aria-label="Recebimentos e valores pendentes nos últimos seis meses">${series.map(x=>`<div class="chart-group"><span class="sr-only">${E(x.label)}: recebido ${C.money(x.paid)}, pendente ${C.money(x.pending)}.</span><span class="chart-bar" style="height:${x.paid?Math.max(3,x.paid/max*100):0}%" title="Recebido em ${E(x.label)}: ${C.money(x.paid)}"></span><span class="chart-bar pending" style="height:${x.pending?Math.max(3,x.pending/max*100):0}%" title="Pendente em ${E(x.label)}: ${C.money(x.pending)}"></span><span class="chart-label">${E(x.label)}</span></div>`).join('')}</div><div class="chart-legend"><span><i class="legend-dot"></i>Recebido</span><span><i class="legend-dot pending"></i>Pendente</span></div><p class="help">Recebidos usam a data de pagamento quando disponível; pendentes usam o vencimento.</p></div>`;}
function healthWidget(rows){const h=Advanced.health(Store.get(),rows),total=h.paid.length+h.pending.length+h.late.length;if(!total)return '<div class="empty"><h3>Sem cobranças no período</h3><p>Altere o período ou cadastre uma cobrança.</p></div>';const paid=Math.round(h.paid.length/total*100),pending=paid+Math.round(h.pending.length/total*100);return `<div class="panel-body"><div class="donut-layout"><div class="donut" style="--paid:${paid}%;--pending:${pending}%"><strong><span data-count="${h.delinquency}">${h.delinquency}</span>%<small>inadimplência</small></strong></div><div><div class="row-item"><span>Pago</span><strong>${h.paid.length}</strong></div><div class="row-item"><span>Pendente</span><strong>${h.pending.length}</strong></div><div class="row-item"><span>Atrasado</span><strong>${h.late.length}</strong></div><div class="row-item"><span>Total previsto</span><strong class="money">${C.money(h.expected)}</strong></div></div></div><p class="help">Taxa = cobranças atrasadas ÷ cobranças vencidas até hoje.</p></div>`;}
function lateClientsWidget(){const items=Advanced.lateClients(Store.get()).slice(0,5);return `<div class="panel-body">${items.map((item,index)=>`<div class="row-item"><div><strong>${index+1}. <a href="#cliente/${encodeURIComponent(item.id)}/cobrancas">${E(item.name)}</a></strong><p class="help">${item.count} cobrança(s) · maior atraso: ${item.days} dia(s)</p></div><strong class="money">${C.money(item.amount)}</strong></div>`).join('')||'<p class="muted">Nenhum cliente com cobrança atrasada.</p>'}<p class="help">Ordenado pelo maior tempo em atraso e depois pelo valor.</p></div>`;}
function calendarWidget(){const s=Store.get();if(!calendarMonth)calendarMonth=s.today.slice(0,7);const cal=Advanced.calendar(s,calendarMonth),week=['D','S','T','Q','Q','S','S'];return `<div class="panel-body"><div class="calendar-head"><button class="btn small" data-action="calendar-prev" aria-label="Mês anterior">←</button><strong>${E(cal.label)}</strong><button class="btn small" data-action="calendar-next" aria-label="Próximo mês">→</button></div><div class="calendar-grid" role="grid" aria-label="Calendário de ${E(cal.label)}">${week.map(day=>`<span class="calendar-weekday" aria-hidden="true">${day}</span>`).join('')}${Array.from({length:cal.leading},()=>'<span class="calendar-day empty"></span>').join('')}${Array.from({length:cal.total},(_,i)=>{const day=i+1,date=cal.month+'-'+String(day).padStart(2,'0'),bills=cal.byDay.get(day)||[];return `<button class="calendar-day ${date===s.today?'today':''}" data-action="calendar-day" data-id="${E(bills[0]?.id||'')}" ${bills.length?'':'disabled'} aria-label="${day} de ${E(cal.label)}: ${bills.length} cobrança(s)"><span>${day}</span><span class="calendar-dots" aria-hidden="true">${bills.slice(0,5).map(b=>`<i class="calendar-dot ${b.paid?'paid':b.due<s.today?'late':''}"></i>`).join('')}</span></button>`;}).join('')}</div><p class="help">Verde: pago · amarelo: pendente · vermelho: atrasado.</p></div>`;}