'use strict';
document.addEventListener('submit',async e=>{if(!e.target.matches('form'))return;e.preventDefault();let form=e.target,f=new FormData(form);try{switch(form.id){
case 'client-form':reviewClient(form);break;
case 'profile-form':await commit('profile',{name:f.get('profile-name').trim(),company:f.get('profile-company').trim(),initials:f.get('profile-initials').trim().toUpperCase(),accent:f.get('accent')},'Identidade visual salva');break;
case 'filters-form':{let from=f.get('from'),to=f.get('to');if(from&&to&&from>to)throw Error('A data inicial deve ser anterior à final.');Filters.set({status:f.getAll('status'),plan:f.getAll('plan'),owner:f.getAll('owner'),tags:f.getAll('tags'),from,to,category:f.get('category'),active:f.has('inactive')?'all':'active'});closeModal();render();break;}
case 'bill-form':await commit('save_bill',{clientId:f.get('clientId'),amount:Math.round(Number(f.get('bill-amount'))*100),due:f.get('bill-due'),plan:f.get('bill-plan')||f.get('plan')},'Cobrança criada');break;
case 'reminder-form':await commit('settings',{skipPaid:true,rules:Store.get().settings.rules.map(r=>({...r,time:f.get(r.key+'-time'),enabled:f.has(r.key+'-enabled')}))},'Regras salvas');break;
case 'templates-form':await commit('settings',{templates:Object.fromEntries(f.entries())},'Modelos manuais salvos');break;
case 'timezone-form':await commit('settings',{timezone:f.get('timezone')},'Fuso atualizado');break;
case 'taxonomy-form':{let kind=form.dataset.kind,id=form.dataset.id,old=Store.get()[kind].find(t=>t.id===id);await commit('taxonomy',{kind,item:{id:id||undefined,name:f.get('taxonomy-name').trim(),parent:f.get('parent')||'',archived:old?.archived||false}},'Classificação salva');break;}
case 'view-form':{let views=Store.get().views.slice(),id=form.dataset.id,old=views.find(v=>v.id===id),name=f.get('view-name').trim();if(!name)throw Error('Informe um nome.');let v={id:id||Store.id(),name,favorite:f.has('favorite'),filters:old?.filters||Filters.saved()};views=old?views.map(x=>x.id===id?v:x):[...views,v];await commit('views',{views},'Visão salva');break;}
}}catch(err){error(err.message);}});
document.addEventListener('input',e=>{if(e.target.id==='search'){clearTimeout(searchTimer);searchTimer=setTimeout(()=>{Filters.set({q:e.target.value});refreshList();},250);}if(e.target.id==='command-search')$('#command-list').innerHTML=commandItems(e.target.value);if(e.target.closest('#templates-form')){let s=Store.get();if(s.clients[0]&&s.bills[0])$('#template-preview').textContent=C.message(s.clients[0],s.bills[0],e.target.value);}});
document.addEventListener('change',e=>{let t=e.target;if(t.dataset.pref)Preferences.set({[t.dataset.pref]:t.value});if(t.id==='sort'){Filters.set({sort:t.value});refreshList();}if(t.id==='select-all'){const rows=Filters.apply();rows.forEach(b=>t.checked?selectedBills.add(b.id):selectedBills.delete(b.id));refreshList();}if(t.classList.contains('bill-select')){t.checked?selectedBills.add(t.value):selectedBills.delete(t.value);const bar=$('#bulk-bar');if(bar)bar.hidden=!selectedBills.size;if($('#bulk-count'))$('#bulk-count').textContent=selectedBills.size;}if(t.id==='dashboard-period')editingDashboard.period=t.value;if(t.dataset.widgetVisible)editingDashboard.widgets.find(w=>w.id===t.dataset.widgetVisible).visible=t.checked;if(t.dataset.widgetSize)editingDashboard.widgets.find(w=>w.id===t.dataset.widgetSize).size=t.value;if(t.id==='suggestions-enabled'){suggestionsEnabled=t.checked;render();}});
let dragId='';document.addEventListener('dragstart',e=>{let row=e.target.closest('[data-widget]');if(row){dragId=row.dataset.widget;row.classList.add('dragging');e.dataTransfer.setData('text/plain',dragId);}});document.addEventListener('dragover',e=>{if(e.target.closest('[data-widget]'))e.preventDefault();});document.addEventListener('drop',e=>{let row=e.target.closest('[data-widget]');if(row&&dragId){e.preventDefault();let a=editingDashboard.widgets.findIndex(w=>w.id===dragId),b=editingDashboard.widgets.findIndex(w=>w.id===row.dataset.widget);if(a>=0&&b>=0){let [item]=editingDashboard.widgets.splice(a,1);editingDashboard.widgets.splice(b,0,item);drawCustomize();$('#announce').textContent='Ordem dos blocos atualizada.';}dragId='';}});document.addEventListener('dragend',()=>$$('.dragging').forEach(x=>x.classList.remove('dragging')));
window.addEventListener('hashchange',()=>{if(location.hash==='#main')return;if($('#dialog').open)$('#dialog').close();render();$('h1')?.focus();window.scrollTo(0,0);});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#app').classList.contains('menu-open')){$('#app').classList.remove('menu-open');$('.mobile-menu').setAttribute('aria-expanded','false');syncMenu();$('.mobile-menu').focus();}});
window.addEventListener('appearancechange',async e=>{if(!e.detail.saved)toast('Preferência aplicada apenas nesta aba.');if(Store.real){try{await Store.mutate('preferences',e.detail.value);}catch(_){toast('Aparência aplicada; não foi possível sincronizar a conta.');}}});
$('#dialog').addEventListener('cancel',e=>{if(busy)e.preventDefault();});$('#dialog').addEventListener('close',()=>modalReturn?.focus());
window.addEventListener('resize',syncMenu);document.addEventListener('keydown',e=>{if(e.key==='Tab'&&matchMedia('(max-width:600px)').matches&&$('#app').classList.contains('menu-open')){const items=$$('.sidebar a,.sidebar button');const first=items[0],last=items[items.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('online',()=>updateConnection());window.addEventListener('offline',()=>updateConnection());
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installPrompt=e;$('#install-app')?.removeAttribute('hidden');});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();commandPalette();}});

shell();syncMenu();reload();